### ISSUE TITLE
Pytorch<1.8 not working despite requirements.txt

### ISSUE THREAD

**Issue by charlielito** [PyTorchLightning/metrics#1034]
## 🐛 Bug

In `requirements.txt` you depend on torch>=1.3.1 but while trying to use torchmetrics with torch1.4 I encountered an error in https://github.com/PyTorchLightning/metrics/blob/master/torchmetrics/utilities/data.py#L242 because `are_deterministic_algorithms_enabled` function is only available for torch>=1.8

### To Reproduce

Install torchmetrics and torch<1.8 and run the provided script.

#### Code sample

```python
import torch
from torchmetrics.functional import confusion_matrix
x = torch.tensor([[1, 2, 3], [1, 2, 3]]).cuda()
y = torch.tensor([[1, 2, 3], [1, 2, 3]]).cuda()
confusion_matrix(x, y, num_classes=4)
```

### Expected behavior

Should run.

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source): pip install torchmetrics~=0.7.2 
- Python & PyTorch Version (e.g., 1.0): python3.7 and pytorch1.4
- Any other relevant information such as OS (e.g., Linux): Ubuntu 20.04

**Comment by Borda** [comment]
I canot reproduce the issue :(
```py
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.__version__
'1.4.0'
>>> import torchmetrics
>>> torchmetrics.__version__
'0.7.2'
>>> from torchmetrics.functional import confusion_matrix
>>> x = torch.tensor([[1, 2, 3], [1, 2, 3]]).cuda()
>>> y = torch.tensor([[1, 2, 3], [1, 2, 3]]).cuda()
>>> confusion_matrix(x, y, num_classes=4)
tensor([[0, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 2, 0],
        [0, 0, 0, 2]], device='cuda:0')
```

**Comment by charlielito** [comment]
That's weird :s What cuda version do you have?

```python
Python 3.7.13 (default, Mar 29 2022, 02:18:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.__version__
'1.4.0'
>>> torch.version.cuda
'10.1'
>>> import torchmetrics
>>> torchmetrics.__version__
'0.7.3'
>>> from torchmetrics.functional import confusion_matrix
>>> x = torch.tensor([[1, 2, 3], [1, 2, 3]]).cuda()
>>> y = torch.tensor([[1, 2, 3], [1, 2, 3]]).cuda()
>>> confusion_matrix(x, y, num_classes=4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/charlie/miniconda3/envs/semantic-segmentation/lib/python3.7/site-packages/torchmetrics/functional/classification/confusion_matrix.py", line 184, in confusion_matrix
    confmat = _confusion_matrix_update(preds, target, num_classes, threshold, multilabel)
  File "/home/charlie/miniconda3/envs/semantic-segmentation/lib/python3.7/site-packages/torchmetrics/functional/classification/confusion_matrix.py", line 49, in _confusion_matrix_update
    bins = _bincount(unique_mapping, minlength=minlength)
  File "/home/charlie/miniconda3/envs/semantic-segmentation/lib/python3.7/site-packages/torchmetrics/utilities/data.py", line 262, in _bincount
    if x.is_cuda and torch.are_deterministic_algorithms_enabled():
AttributeError: module 'torch' has no attribute 'are_deterministic_algorithms_enabled'
```
