### ISSUE TITLE
Retrieval metrics problem with pytorch lightning integration in compute()

### ISSUE THREAD

**Issue by gatoniel** [PyTorchLightning/metrics#152]
## 🐛 Bug

I use the commit https://github.com/PyTorchLightning/metrics/commit/f06488faf79d4f4792cd392e964870d4898dde45 to calculate `RetrievalMAP` and `RetrievalPrecision` in a pytorch-lightning module. The `validation_step` and `validation_step_end` functions work, but the `fast_dev_run=True` gives an error in the `compute()` step.

However, when I run `self.log("val_MAP", self.metric.compute())` instead of `self.log("val_MAP", self.metric)` in the `validation_step_end` I do not get errors. But computing the whole metric is becoming very slow if it is done every validation_step.

### To Reproduce

I run the following code with the mentioned commit. 

#### Code sample

```python
from typing import Optional
import os
import torch
from torch import nn
import torch.nn.functional as F
from torchvision import transforms
from torchvision.datasets import MNIST
from torch.utils.data import DataLoader, random_split
import pytorch_lightning as pl

from torchmetrics import (
    RetrievalMAP,
    RetrievalPrecision,
    MeanAbsoluteError,
)


class MNISTDataModule(pl.LightningDataModule):
    def __init__(self, batch_size=32):
        super().__init__()
        self.batch_size = batch_size

    def prepare_data(self):
        MNIST(os.getcwd(), train=True, download=True)
        MNIST(os.getcwd(), train=False, download=True)

    def setup(self, stage: Optional[str] = None):
        transform = transforms.Compose(
            [transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))]
        )
        if stage == "fit":
            mnist_train = MNIST(os.getcwd(), train=True, transform=transform)
            self.mnist_train, self.mnist_val = random_split(
                mnist_train, [55000, 5000]
            )
        if stage == "test":
            self.mnist_test = MNIST(
                os.getcwd(), train=False, transform=transform
            )

    def train_dataloader(self):
        mnist_train = DataLoader(self.mnist_train, batch_size=self.batch_size)
        return mnist_train

    def val_dataloader(self):
        mnist_val = DataLoader(self.mnist_val, batch_size=self.batch_size)
        return mnist_val

    def test_dataloader(self):
        mnist_test = DataLoader(self.mnist_test, batch_size=self.batch_size)
        return mnist_test


class LitAutoEncoder(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(28 * 28, 64), nn.ReLU(), nn.Linear(64, 1), nn.Softplus()
        )
        self.decoder = nn.Sequential(
            nn.Linear(1, 64), nn.ReLU(), nn.Linear(64, 28 * 28)
        )
        # self.metric = RetrievalMAP()
        self.metric = RetrievalPrecision()
        # self.metric = MeanAbsoluteError()

    def forward(self, x):
        embedding = self.encoder(x)
        return embedding

    def training_step(self, batch, batch_idx):
        x, y = batch
        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = F.mse_loss(x_hat, x)
        self.log("train_loss", loss)
        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch
        x = x.view(x.size(0), -1)
        preds = self.encoder(x).squeeze()

        indexes = torch.randint(100, size=preds.size())
        targets = torch.randint(2, size=preds.size()).to(bool)

        return {"indexes": indexes, "preds": preds, "targets": targets}

    def validation_step_end(self, outputs):
        self.metric(outputs["indexes"], outputs["preds"], outputs["targets"])
        # self.metric(outputs["preds"], outputs["preds"] ** 2)
        self.log("val_MAP", self.metric)
        # self.log("val_MAP", self.metric.compute())

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer


if __name__ == "__main__":
    datamodule = MNISTDataModule()
    module = LitAutoEncoder()

    trainer = pl.Trainer(gpus=1, fast_dev_run=True)

    trainer.fit(module, datamodule=datamodule)
    trainer.test(module, datamodule=datamodule)
```

#### StackTrace

```
Traceback (most recent call last):
  File "reproduce_retrieval_error.py", line 107, in <module>
    trainer.fit(module, datamodule=datamodule)
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 577, in run_training_epoch
    self.trainer.run_evaluation(on_epoch=True)
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 754, in run_evaluation
    eval_loop_results = self.evaluation_loop.log_epoch_metrics_on_evaluation_end()
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 200, in log_epoch_metrics_on_evaluation_end
    eval_loop_results = self.trainer.logger_connector.get_evaluate_epoch_results()
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 286, in get_evaluate_epoch_results
    metrics_to_log = self.cached_results.get_epoch_log_metrics()
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/epoch_result_store.py", line 405, in get_epoch_log_metrics
    return self.run_epoch_by_func_name("get_epoch_log_metrics")
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/epoch_result_store.py", line 398, in run_epoch_by_func_name
    results = [func() for func in results]
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/epoch_result_store.py", line 398, in <listcomp>
    results = [func() for func in results]
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/epoch_result_store.py", line 128, in get_epoch_log_metrics
    return self.get_epoch_from_func_name("get_epoch_log_metrics")
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/epoch_result_store.py", line 121, in get_epoch_from_func_name
    self.run_epoch_func(results, opt_metrics, func_name, *args, **kwargs)
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/epoch_result_store.py", line 110, in run_epoch_func
    metrics_to_log = func(*args, add_dataloader_idx=self.has_several_dataloaders, **kwargs)
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/pytorch_lightning/core/step_result.py", line 327, in get_epoch_log_metrics
    result[dl_key] = self[k].compute().detach()
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/torchmetrics/metric.py", line 228, in wrapped_func
    self._computed = compute(*args, **kwargs)
  File "/home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8/lib/python3.8/site-packages/torchmetrics/retrieval/retrieval_metric.py", line 110, in compute
    idx = torch.cat(self.idx, dim=0)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradNestedTensor, UNKNOWN_TENSOR_TYPE_ID, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /pytorch/build/aten/src/ATen/RegisterCPU.cpp:5925 [kernel]
CUDA: registered at /pytorch/build/aten/src/ATen/RegisterCUDA.cpp:7100 [kernel]
QuantizedCPU: registered at /pytorch/build/aten/src/ATen/RegisterQuantizedCPU.cpp:641 [kernel]
BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9122 [autograd kernel]
AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9122 [autograd kernel]
AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9122 [autograd kernel]
AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9122 [autograd kernel]
AutogradNestedTensor: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9122 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9122 [autograd kernel]
AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9122 [autograd kernel]
AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9122 [autograd kernel]
AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9122 [autograd kernel]
Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_2.cpp:10525 [kernel]
Autocast: registered at /pytorch/aten/src/ATen/autocast_mode.cpp:254 [kernel]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:1016 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
```

### Expected behavior

This error should not show up. I expect the metric to be computed correctly. When I use the `MeanAbsoluteError` as metric the code works. Therefore, there must be a bug in the `compute` step of the Retrieval Metrics in combination with pytorch-lightnings API as a call to `compute()` within the `validation_step_end` does not create errors.

### Environment

 - PyTorch Version (e.g., 1.0): 1.8.1+cu102
 - OS (e.g., Linux): Ubuntu on WSL2
 - How you installed PyTorch (`conda`, `pip`, source): pip / poetry
 - Build command you used (if compiling from source):
 - Python version: 3.8.8
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 1 GPU
 - Any other relevant information:

**Comment by gatoniel** [comment]
Actually, the above example does not work properly with the mentioned `MeanAbsoluteError` either. It produces NaNs.

The `MeanAbsoluteError` metric produces NaNs in `compute` if it is set back to its default values.

The default value for `self.idx` of the `RetrievalMAP` is an empty list. I assume that in `trainer.run_evaluation` (https://github.com/PyTorchLightning/pytorch-lightning/blob/a72a7992a283f2eb5183d129a8cf6466903f1dc8/pytorch_lightning/trainer/trainer.py#L636) the metrics are set back before they are logged in this line https://github.com/PyTorchLightning/pytorch-lightning/blob/a72a7992a283f2eb5183d129a8cf6466903f1dc8/pytorch_lightning/trainer/trainer.py#L719 .

But I do not understand the pytorch-lightning code base and where the metrics are actually set back to their default state, neither do I know if this is rather an issue for pytorch-lightning.

**Comment by lucadiliello** [comment]
Which version of `pytorch-lightning` are you using? I cannot reproduce your error by installing `torchmetrics` both from your commit and from master and with `pytorch-lightning-1.2.6`. `Retrieval` metrics had problem with `fast_dev_run` because with the `skip` action there could have been cases with empty tensors. But know they should be solved (and tested).

**Comment by gatoniel** [comment]
That´s odd, I have pytorch-lightning version 1.2.6 installed.

**Comment by SkafteNicki** [comment]
Cannot reproduce either using latest master of both `torchmetrics` and `pytorch-lightning`.

**Comment by gatoniel** [comment]
I am sorry, but I just created a new conda environment with python 3.8, installed torch and the latest branches of `torchmetrics` and `pytorch-lightning` via pip. Then I copied the above code into a new file and ran it. I got the same error as reported above.

Is this function correct

```
    def validation_step_end(self, outputs):
        self.metric(outputs["indexes"], outputs["preds"], outputs["targets"])
        self.log("val_MAP", self.metric)
```

or should `self.log("val_MAP", self.metric)` not be called here?

**Comment by lucadiliello** [comment]
Please check whether `outputs["indexes"]`, `outputs["preds"]` and `outputs["targets"]` are not empty.

```python
def validation_step_end(self, outputs):
    print(outputs)
    self.metric(outputs["indexes"], outputs["preds"], outputs["targets"])
    self.log("val_MAP", self.metric)
```

**Comment by gatoniel** [comment]
Hi, they are not empty.

As I said, the metric collects the values and calculates them when calling `self.metric.compute()´ in the `validation_epoch_end` function.

**Comment by SkafteNicki** [comment]
@gatoniel can I ask why you are actually using `validation_step_end` and not putting all the code in `validation_step`?

**Comment by gatoniel** [comment]
I wanted to prepare the metric for use in data parallel mode as explained in the last note here https://torchmetrics.readthedocs.io/en/stable/pages/lightning.html

This gives the same error:
```
    def validation_step(self, batch, batch_idx):
        x, y = batch
        x = x.view(x.size(0), -1)
        preds = self.encoder(x).squeeze()

        indexes = torch.randint(100, size=preds.size())
        targets = torch.randint(2, size=preds.size()).to(bool)

        print(indexes, preds, targets)
        self.metric(indexes, preds, targets)
        self.log("val_MAP", self.metric)
```
But this runs without problems:
```
    def validation_step(self, batch, batch_idx):
        x, y = batch
        x = x.view(x.size(0), -1)
        preds = self.encoder(x).squeeze()

        indexes = torch.randint(100, size=preds.size())
        targets = torch.randint(2, size=preds.size()).to(bool)

        print(indexes, preds, targets)
        self.metric(indexes, preds, targets)

    def validation_epoch_end(self, outputs):
        self.log("val_MAP", self.metric.compute())
```
Then again using only
```
    def validation_epoch_end(self, outputs):
        self.log("val_MAP", self.metric)
```
gives the error.

**Comment by lucadiliello** [comment]
Hi @gatoniel . Sorry but I still cannot reproduce your error. What I believe is that you are calling `.compute()` on a metric that didn't receive and `update` yet (it was not provided with data). Please try again by installing from `master` branch because we pushed a lot of updates yesterday.

Btw, I do not understand why you are using the `indexes` in this way. Did you set them to random values only for testing purposes? Otherwise I suggest to wait for the release of `0.3.0` to see examples in the documentation. `indexes` are used to group queries because IR metrics work at the query level and not at the example level.

For example, if your batch is composed by 5 examples:

> (query 1, document 1) -> NN -> relevance score
> (query 1, document 2) -> NN -> relevance score
> (query 2, document 1) -> NN -> relevance score
> (query 2, document 2) -> NN -> relevance score
> (query 2, document 3) - > NN -> relevance score

You should use `indexes = tensor([0, 0, 1, 1, 1])`.

**Comment by gatoniel** [comment]
Hi, yes, I just used random indexes for testing purposes.

I will try to reproduce with the boring model on colab and then share the notebook.

Yes, I think the problem is that the metric did not receive updates. But I think this is because the metric was set back to defaults in the epoch_end call so that all values it received during the epoch are erased.

**Comment by lucadiliello** [comment]
It could be an explanation but it does not explain why we cannot reproduce this error with the same `pytorch-lightning` and `torchmetrics` versions. Using Colab to reproduce is a fantastic idea :).
P.s. `torchmetrics==0.3.0rc0` is out.

**Comment by SkafteNicki** [comment]
Hi @gatoniel 
So after a longer investigation it seemed this is a general problem, that due to some changes in torchmetrics (not related to retrieval metrics) passing a metric object directly to `self.log` in lightning resulted in that error.
This PR on the lightning side will solve the error:
https://github.com/PyTorchLightning/pytorch-lightning/pull/7055
