### ISSUE TITLE
MetricCollection returns None

### ISSUE THREAD

**Issue by IgorHoholko** [PyTorchLightning/metrics#184]
## 🐛 Bug

MetricCollection fails to be logged.

### To Reproduce

```python
metrics = MetricCollection({'accuracy': Accuracy(compute_on_step=False)})

self.train_metrics = metrics.clone(prefix='train_')
self.val_metrics = metrics.clone(prefix='val_')
self.test_metrics = metrics.clone(prefix='test_')

def training_step(self, batch, batch_idx):  # pylint: disable=unused-argument
    x, y = batch['image'], batch['label']
    out = self(x)
    logits = torch.nn.functional.softmax(out, dim=-1)
    loss = self.loss_fn(logits, y)

    metrics_output = self.train_metrics(logits, y)
    self.log_dict(metrics_output, on_step=False, on_epoch=True)
    self.log("train_loss", loss)

    return {'loss':loss, 'y':y, 'logits': logits}
```

### Expected behavior
```
> Traceback (most recent call last):
  File "/home/ihar.khakholka/Projects/attributes/training/run_experiment.py", line 139, in <module>
    main()
  File "/home/ihar.khakholka/Projects/attributes/training/run_experiment.py", line 124, in main
    trainer.fit(lit_model, datamodule=data)
  File "/home/ihar.khakholka/Projects/attributes/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/ihar.khakholka/Projects/attributes/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/ihar.khakholka/Projects/attributes/venv/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/ihar.khakholka/Projects/attributes/venv/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/ihar.khakholka/Projects/attributes/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "/home/ihar.khakholka/Projects/attributes/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 557, in run_training_epoch
    self.on_train_epoch_end(epoch_output)
  File "/home/ihar.khakholka/Projects/attributes/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 802, in on_train_epoch_end
    self.trainer.logger_connector.on_train_epoch_end()
  File "/home/ihar.khakholka/Projects/attributes/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 373, in on_train_epoch_end
    self.cached_results.has_batch_loop_finished = True
  File "/home/ihar.khakholka/Projects/attributes/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/logger_connector/epoch_result_store.py", line 386, in has_batch_loop_finished
    self.auto_reduce_results_on_epoch_end()
  File "/home/ihar.khakholka/Projects/attributes/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/logger_connector/epoch_result_store.py", line 376, in auto_reduce_results_on_epoch_end
    hook_result.auto_reduce_results_on_epoch_end()
  File "/home/ihar.khakholka/Projects/attributes/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/logger_connector/epoch_result_store.py", line 175, in auto_reduce_results_on_epoch_end
    tbptt_outputs = type(tbptt_outputs[0]).reduce_across_time(tbptt_outputs)
  File "/home/ihar.khakholka/Projects/attributes/venv/lib/python3.7/site-packages/pytorch_lightning/core/step_result.py", line 591, in reduce_across_time
    value = torch.tensor(value)
RuntimeError: Could not infer dtype of NoneType
```
or same `you tried to log None which is not currently supported. Try a dict or a scalar/tensor.`

Process finished with exit code 1

### Additional
metrics_output = {'train_accuracy': None}
during train steps. But I think it is okay as compute_on_step=False

### Environment

 - torchmetrics-0.3.0rc1
 - pytorch-lightning==1.2.7

**Comment by SkafteNicki** [comment]
You have set `compute_on_step=False` in the `Accuracy` metric, so calling `forward` will just update the global metric states (equal to just calling `update`). If you want a metric to return something when calling `forward` set `compute_on_step=True` (default value for most metrics).

**Comment by Borda** [comment]
@IgorHoholko feel free to reopen if needed :rabbit:

**Comment by IgorHoholko** [comment]
@SkafteNicki Thank you.
It works in the way you said.

But if I want to **update** metric each step, but **compute** and log just once. What is the best way to do this? 
Have I got properly, that when `compute_on_step=False` any metrics is just *extending* its internal state with **y** and **logits** and each new epoch it resets its internal state?

 If so,  can I keep  `compute_on_step=False` and then at `on_epoch_end` call `compute()` directly and log it?

**Comment by SkafteNicki** [comment]
If you just want to update the metric states over the hole epoch, and log the final value you can just do:
```python
self.train_metrics.update(logits, y) # or self.train_metrics(logits, y) if compute_on_step=False
self.log_dict(metrics_output, on_step=False, on_epoch=True)
```

**Comment by IgorHoholko** [comment]
@SkafteNicki  But looks like my code and I got an error in this way :)

**Comment by SkafteNicki** [comment]
sorry, I was a little too fast with the typing :]
Try something like this:
```python
def training_step(self, batch, batch_idx):
    ...
    self.train_metrics.update(logits, y)
    ...

def training_epoch_end(self, outputs):
    self.log_dict(self.train_metrics.compute())
```

**Comment by IgorHoholko** [comment]
@SkafteNicki, okay, thank you :)
