### ISSUE TITLE
PearsonCorrcoef will break when single sample is passed at a time.

### ISSUE THREAD

**Issue by ramonemiliani93** [PyTorchLightning/metrics#227]
## 🐛 Bug

When passing a single sample at a time to the `PearsonCorrcoef` metric it will crash. I am not sure if this is the intended behavior but it causes problems for big models training with batch size of one.

### To Reproduce
```
import torchmetrics
correlation = torchmetrics.PearsonCorrcoef()

# Works
correlation.update(torch.tensor([0.3, 0.7, 0.9]), torch.tensor([0.4, 0.5, 0.4]))
correlation.compute()

# Crashes
correlation.update(torch.tensor([0.3]), torch.tensor([0.4]))
correlation.update(torch.tensor([0.7]), torch.tensor([0.5]))
correlation.update(torch.tensor([0.9]), torch.tensor([0.4]))
correlation.compute()
```

Error Message:
`RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated`

**Comment by raimis** [comment]
@Borda #229 is in `v3.2.0` (https://github.com/PyTorchLightning/metrics/commits/v0.3.2), but the issue isn't fixed:

```python
import torch
import torchmetrics

print(torch.__version__)
print(torchmetrics.__version__)

correlation = torchmetrics.PearsonCorrcoef()

correlation.update(torch.tensor([0.3]), torch.tensor([0.4]))
correlation.update(torch.tensor([0.7]), torch.tensor([0.5]))
correlation.update(torch.tensor([0.9]), torch.tensor([0.4]))
correlation.compute()
```
Output:
```
1.8.0
0.3.2
/shared/raimis/opt/miniconda/envs/tmp/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `PearsonCorrcoef` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
Traceback (most recent call last):
  File "bug.py", line 12, in <module>
    correlation.compute()
  File "/shared/raimis/opt/miniconda/envs/tmp/lib/python3.8/site-packages/torchmetrics/metric.py", line 251, in wrapped_func
    self._computed = compute(*args, **kwargs)
  File "/shared/raimis/opt/miniconda/envs/tmp/lib/python3.8/site-packages/torchmetrics/regression/pearson.py", line 95, in compute
    preds = torch.cat(self.preds, dim=0)
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated
```
