### ISSUE TITLE
list index out of range when using ModuleDict with DDP

### ISSUE THREAD

**Issue by chris-tkinter** [PyTorchLightning/metrics#409]
## 🐛 Bug

Hi, I am using the torchmetrics with torch-lightning. 
I have a `LightningModule` that needs several metrics, and when I register the `MetricCollection` with `ModuleDict`, it is fine in the non-ddp mode, however if I use `accelerator='ddp'`, there is the following error
```
Traceback (most recent call last):
  File "/home/tchrs/meta/lightning-hydra-template/run.py", line 30, in main
    return train(config)
  File "/home/tchrs/meta/lightning-hydra-template/src/train.py", line 77, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self._run(model)
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 755, in _run
    self.pre_dispatch()
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 780, in pre_dispatch
    self.accelerator.pre_dispatch(self)
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 108, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 290, in pre_dispatch
    self.configure_ddp()
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 257, in configure_ddp
    **self._ddp_kwargs,
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 446, in __init__
    self._sync_params_and_buffers(authoritative_rank=0)
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 452, in _sync_params_and_buffers
    for name, param in self.module.state_dict().items():
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1076, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1076, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1076, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  [Previous line repeated 1 more time]
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/torchmetrics/metric.py", line 421, in state_dict
    with self.sync_context(dist_sync_fn=self.dist_sync_fn):
  File "/home/jiashu/.conda/envs/meta/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/torchmetrics/metric.py", line 303, in sync_context
    distributed_available=distributed_available
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/torchmetrics/metric.py", line 272, in sync
    self._sync_dist(dist_sync_fn, process_group=process_group)
  File "/home/tchrs/.conda/envs/meta/lib/python3.7/site-packages/torchmetrics/metric.py", line 222, in _sync_dist
    if isinstance(output_dict[attr][0], Tensor):
IndexError: list index out of range
```

### To Reproduce

Define a model like this
```python

class MNISTLitModel(LightningModule):
    def __init__(
        self,
        input_size: int = 784,
        lin1_size: int = 256,
        lin2_size: int = 256,
        lin3_size: int = 256,
        output_size: int = 10,
        lr: float = 0.001,
        weight_decay: float = 0.0005,
    ):
        super().__init__()

        self.save_hyperparameters()

        self.model = SimpleDenseNet(hparams=self.hparams)

        # loss function
        self.criterion = torch.nn.CrossEntropyLoss()

        m = MetricCollection([
            Accuracy()
        ])
        a = MetricCollection([
            AUROC()
        ])
        self.metrics = ModuleDict()
        for phase in ["train", "valid", "test"]:
            self.metrics[f"{phase}_pred"] = m.clone()
            self.metrics[f"{phase}_logits"] = a.clone()

    def forward(self, x: torch.Tensor):
        return self.model(x)

    def step(self, batch: Any):
        x, y = batch
        logits = self.forward(x)
        loss = self.criterion(logits, y)
        preds = torch.argmax(logits, dim=1)
        return loss, logits, preds, y

    def training_step(self, batch: Any, batch_idx: int):
        loss, logits, preds, targets = self.step(batch)
        return {"loss": loss, "logits": logits, "preds": preds, "targets": targets}

    def compute_metric_and_log(self, output: dict, phase: str):
           loss,  logits, pred, label = output["loss"], output["logits"], output["preds"], output["targets"]
  
          for type_ in ['pred', 'logit']:
              input = logits if type_ == "logit" else pred
              metric = self.metrics[f"{phase}_{input}"]
              metric(input, label)
              for mname, m in metric.items():
                  self.log(f"{phase}/{mname}", m, logger=True, on_step=phase == "train", on_epoch=phase != "train")

    def training_step_end(self, output: dict) -> dict:
        self.compute_metric_and_log(output, "train")
        return output

....
```

### Environment

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): n/a
 - Python version: 3.7,10
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: GTX 1080 Ti
 - Any other relevant information: 
 torch lightning version 1.3.8
 
torchmetrics version 0.4.0

**Comment by Borda** [comment]
@SkafteNicki @awaelchli could have look?

**Comment by awaelchli** [comment]
Is this unrelated to the state_dict issues we had with torchmetrics 0.4 + PL? I believe 0.4.0 + 1.3.8 was no good.

**Comment by awaelchli** [comment]
unrelated to the error but I believe you would run into this issue later on: make sure to reduce the outputs in `training_step_end`. I recommend only returning loss.mean() unless you need the other outputs in on of the epoch_end hooks.
