### ISSUE TITLE
TorchMetrics 0.5.1 no longer works with PL save_hyperparameters

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/metrics#492]
## 🐛 Bug

The Metric object can no longer be dumped with yaml.

After a `git bisect` it seems the bug was introduced in #462

### To Reproduce

```
>>> from torchmetrics import Accuracy
>>> import yaml
>>> yaml.dump(Accuracy())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ethan/miniconda3/envs/py38/lib/python3.8/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/Users/ethan/miniconda3/envs/py38/lib/python3.8/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/Users/ethan/miniconda3/envs/py38/lib/python3.8/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/Users/ethan/miniconda3/envs/py38/lib/python3.8/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/Users/ethan/miniconda3/envs/py38/lib/python3.8/site-packages/yaml/representer.py", line 342, in represent_object
    return self.represent_mapping(
  File "/Users/ethan/miniconda3/envs/py38/lib/python3.8/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/Users/ethan/miniconda3/envs/py38/lib/python3.8/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/Users/ethan/miniconda3/envs/py38/lib/python3.8/site-packages/yaml/representer.py", line 330, in represent_object
    dictitems = dict(dictitems)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

### Additional context

This worked for previous versions

**Comment by SkafteNicki** [comment]
It is caused by this line:
https://github.com/PyTorchLightning/metrics/blob/7b093813e2ae10effe0266015ecd631a5b547123/torchmetrics/metric.py#L87
