### ISSUE TITLE
MeanMetric conflicts with EarlyStopping

### ISSUE THREAD

**Issue by Qcactus** [PyTorchLightning/metrics#611]
## 🐛 Bug

The states in MeanMetric are Tensors, which conflict with the output format of EarlyStopping in pytorch lightning.

#### Code sample

```python
import torch
from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.callbacks import EarlyStopping
from torchmetrics import MeanMetric


class Minimal(LightningModule):
    def __init__(self):
        super().__init__()
        self.params = torch.nn.Parameter(torch.zeros(10))
        self.loss = MeanMetric()

    def train_dataloader(self):
        return [1, 2, 3, 4, 5]

    def training_step(self, batch, batch_idx):
        self.loss(batch)
        self.log("loss", self.loss)

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters())


model = Minimal()
trainer = Trainer(gpus=0, callbacks=[EarlyStopping(monitor="loss")], max_epochs=3)
trainer.fit(model)
```

Output:
```text
...
Epoch 0: 100%|████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.45it/s, loss=nan, v_num=0]Traceback (most recent call last):
  File "/Users/qi/Documents/codes/pl_rec/draft.py", line 26, in <module>
    trainer.fit(model)
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in fit
    self._call_and_handle_interrupt(
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1193, in _run
    self._dispatch()
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1272, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1282, in run_stage
    return self._run_train()
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1312, in _run_train
    self.fit_loop.run()
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 151, in run
    output = self.on_run_end()
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 302, in on_run_end
    self.trainer.call_hook("on_train_epoch_end")
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1477, in call_hook
    callback_fx(*args, **kwargs)
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/callback_hook.py", line 93, in on_train_epoch_end
    callback.on_train_epoch_end(self, self.lightning_module)
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 189, in on_train_epoch_end
    self._run_early_stopping_check(trainer)
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 206, in _run_early_stopping_check
    should_stop, reason = self._evaluate_stopping_criteria(current)
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 241, in _evaluate_stopping_criteria
    reason = self._improvement_message(current)
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 263, in _improvement_message
    msg = f"Metric {self.monitor} improved. New best score: {current:.3f}"
  File "/Users/qi/miniconda3/envs/torch/lib/python3.9/site-packages/torch/_tensor.py", line 572, in __format__
    return object.__format__(self, format_spec)
TypeError: unsupported format string passed to Tensor.__format__
```

### Expected behavior

No conflict.

### Environment

- pytorch 1.10.0  
- pytorch-lightning 1.5.0 
- torchmetrics 0.6.0

### Additional context

This bug does not happen with Accuracy. This is probably because Accuracy defines the default values of states as `torch.tensor(0)` while MeanMetric uses `torch.zeros(1)`.

**Comment by carmocca** [comment]
There are 2 improvements to do here.

1. In Lightning, squeeze the Tensor
2. In torchmetrics, use `torch.tensor(0) == tensor(0)` instead of `torch.zeros(1) == tensor([0])`.

I can open a PR to Lightning for (1).

For (2), after snooping around the codebase, seems like some metrics use one option and other metrics the other. This should probably be fixed for all cc @SkafteNicki 

https://grep.app/search?q=default%3Dtorch.tensor%280&filter[repo][0]=PyTorchLightning/metrics
https://grep.app/search?q=default%3Dtorch.zeros%28&filter[repo][0]=PyTorchLightning/metrics
