### ISSUE TITLE
`ValueError: 0.5/0.75 is not in list` - when passing a custom set of IoU thresholds to `MeanAveragePrecision`

### ISSUE THREAD

**Issue by Chris-hughes10** [PyTorchLightning/metrics#994]
## 🐛 Bug

When I try to use `MeanAveragePrecision` to compute the mAP over a custom range of IoU thresholds, a value error is thrown if `0.5` and `0.75` are not included in the list.

This is due to these values being hardcoded [here](https://github.com/PyTorchLightning/metrics/blob/c494f3575f542e7c264555a71fb97e8676f64700/torchmetrics/detection/mean_ap.py#L656).

### To Reproduce

Steps to reproduce the behavior...

```
Traceback (most recent call last):
 line 27, in <module>
    print(map.compute())
  File "C:\Users\hughesc\Anaconda3\envs\accelerated-dev\lib\site-packages\torchmetrics\metric.py", line 440, in wrapped_func
    value = compute(*args, **kwargs)
  File "C:\Users\hughesc\Anaconda3\envs\accelerated-dev\lib\site-packages\torchmetrics\detection\mean_ap.py", line 766, in compute
    map_val, mar_val = self._summarize_results(precisions, recalls)
  File "C:\Users\hughesc\Anaconda3\envs\accelerated-dev\lib\site-packages\torchmetrics\detection\mean_ap.py", line 656, in _summarize_results
    map_metrics.map_50 = self._summarize(results, True, iou_threshold=0.5, max_dets=last_max_det_thr)
  File "C:\Users\hughesc\Anaconda3\envs\accelerated-dev\lib\site-packages\torchmetrics\detection\mean_ap.py", line 570, in _summarize
    thr = self.iou_thresholds.index(iou_threshold)
ValueError: 0.5 is not in list
```

#### Code sample
```
import torch
from torchmetrics.detection import MeanAveragePrecision

if __name__ == '__main__':

    device = torch.device('cuda:0')

    preds = [
        dict( boxes=torch.tensor([[1.5, 2., 3., 4.]], device=device),
        scores=torch.tensor([0.6], device=device),
        labels=torch.tensor([1], device=device),)
    ]

    targets = [
        dict(boxes=torch.tensor([[1., 2., 3., 4.]], device=device),
             scores=torch.tensor([0.8], device=device),
             labels=torch.tensor([1], device=device), )
    ]

    map = MeanAveragePrecision(class_metrics=True,
                               iou_thresholds=[0.1, 0.2],
                               ).to(device)

    map.update(preds, targets)

    print(map.compute())
```

### Expected behavior

Ideally, I would like to be able to calculate mAP using any custom range of IoU values, or even a single value if it is passed as a list (e.g. `[0.4]`). Although this is a departure from the pycoctools implementation, this would make this metric well suited to use cases outside of the coco competition.

At a minimum, this restriction should be documented, and the error should be handled more gracefully. 

### Environment

- OS (e.g., Linux): Windows, Ubuntu
- Python & PyTorch Version (e.g., 1.0): Python 3.8 & 3.9, PyTorch 1.10
- How you installed PyTorch (`conda`, `pip`, build command if you used source): conda
- Any other relevant information:

**Comment by bepuca** [comment]
I am facing the same issue when passing a single threshold, which I need to do some error analysis.

Maybe a potential solution is to have an optional argument at the beginning set by default at `[0.5, 0.75]` to indicate the desired thresholds to be reported? Then would be possible to iterate over the asked thresholds and report them? If you like the idea, maybe I could give it a go and do a PR.

**Comment by SkafteNicki** [comment]
Hi @Chris-hughes10 and @bepuca,
I created PR #995 to address this. We will simply check for the 0.5 and 0.75 in the list of thresholds and if they are not present we will set them to -1. Hope this works for your both :]

**Comment by bepuca** [comment]
Thank you very much for such a quick response @SkafteNicki !

**Comment by ekmungi** [comment]
I know the issue is closed, but I feel the solution proposed is not the best case. Shouldn't the metric be general enough to provide mAP for any IOU?
